# Scaler Arithmatic

In [7]:
import numpy as np
a = np.array([1, 2, 3])
a = a/2
print(a)

[0.5 1.  1.5]


In [8]:
a= a**2
print(a)

[0.25 1.   2.25]


# Vectorised math func 

In [10]:
radii = np.array([1, 2, 3])
print(np.pi*radii**2)

[ 3.14159265 12.56637061 28.27433388]


# Element wise arithmetic

In [11]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print(array1 + array2)
print(array1 * array2)
print(array1 / array2)


[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


# comparison operators


In [14]:
scores = np.array([90, 80, 70])
print(scores > 80)
print(scores==100)
print(scores[scores > 80])

[ True False False]
[False False False]
[90]
