In [ ]:
import numpy as np
array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array2.shape)
#now we can broadcast the arrays to perform elementwise multiplication beause the shapes are compatible
print(array1 * array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [13]:
array1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
array2 = np.array([[4], [5], [6], [7]])
print(array1.shape)
print(array2.shape)
#the shapes are not compatible for broadcasting
print(array1 * array2)# --- IGNORE ---

(3, 4)
(4, 1)


ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 