filtering = refers to the process of selecting specific elements from an array based on a condition. 

In [13]:
import numpy as np
ages = np.array([[25,18,17, 30, 35, 40], [39, 45,15,18,17, 50, ]])
teenagers = ages[ages < 20]
print(teenagers)
adults = ages[(ages >= 20) & (ages < 40)]
print(adults)
evens = ages[ages % 2 == 0]
print(evens)
odds = ages[ages % 2 != 0]
print(odds)


[18 17 15 18 17]
[25 30 35 39]
[18 30 40 18 50]
[25 17 35 39 45 15 17]


In [17]:
adults = np.where((ages >= 20) & (ages < 40), ages, 0)
print(adults)

[[25  0  0 30 35  0]
 [39  0  0  0  0  0]]
