In [4]:
import numpy as np
print(np.__version__)

2.4.2


In [11]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [12]:

my_list = [1, 2, 3]
my_list = my_list * 2
print(my_list)

[1, 2, 3, 1, 2, 3]


In [13]:
import numpy as np
array = np.array([1, 2, 3])
array = array * 2
print(array)

[2 4 6]


Multidimentional array

In [14]:
import numpy as np
array = np.array([[[1, 2, 3],[2,3,4],[4,5,6]]
                  ,[[1, 2, 3],[2,3,4],[4,5,6]]
                  ,[[1, 2, 3],[2,3,4],[4,5,6]]])
                
print(array.shape)                 
print(array.ndim)
#multidimensional indexing
print(array[0,0,1]) #first 0 refers to the first 2D array, second 0 refers to the first row, and third 0 refers to the first element in that row
print(array[0,1,2] + array[1,1,2] + array[2,1,2])


(3, 3, 3)
3
2
12


In [15]:
import numpy as np
array = np.array([
                  [1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]
                  ])
#array[start:stop:step] 
print(array.ndim)
print(array[1:2:5]) 


2
[[5 6 7 8]]


In [ ]:
np.array(['apple' , 'banana' , 'cherry'] ,dtype ='<U5') #dtype ='<U5' means that the array will contain Unicode strings with a maximum length of 5 characters.


array(['apple', 'banan', 'cherr'], dtype='<U5')

In [27]:
np.array([[[2,3,4]]],ndmin =2) #ndmin = 2 means that the array will have a minimum of 2 dimensions, even if the input data has fewer dimensions. In this case, the input data is a 3D array, but it will be treated as a 2D array with one row and three columns. 
print(array.ndim)

2


In [28]:
np.array([1, 2, 3, 4, 5], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])