In [24]:
import numpy as np
rng = np.random.default_rng()
print(rng.integers(low =0, high =100, size=1))

[0]


In [25]:
#for same value repeat
rng = np.random.default_rng(seed=1) # if we change the seed value we will get different random numbers
print(rng.integers(low =0, high =100, size=(2, 3)))

[[47 51 75]
 [95  3 14]]


In [31]:
print(np.random.uniform(low=0, high=11, size=(2, 3)))

[[1.7881745  7.5891068  7.58019463]
 [1.88227472 4.78237882 8.39341042]]


In [35]:
rng = np.random.default_rng()
fruits = ['apple', 'banana', 'cherry', 'date']
fruit = rng.choice(fruits , size=3)  # randomly select a fruit from the list
print(fruit)

['cherry' 'banana' 'date']
